### ISSUE TITLE
Bugs visuais na tela de salvar / carregar / apagar jogo

### ISSUE THREAD

**Issue by leomontenegro6** [leomontenegro6/megaman-zx-traducao-ptbr#13]
Após a migração da rom americana para a japonesa, surgiram alguns pequenos bugs visuais na tela de salvar / carregar / apagar jogo. A imagem abaixo ilustra os bugs em questão.

Na imagem, a parte da esquerda corresponde à tela na rom japonesa, enquanto que a da direita a americana. Ao comparar ambas as partes, encontrei os seguintes bugs:
1. Onde situa-se o tempo de jogo em horas, a distância entre os separadores (dois pontos e aspas) está um espaço menor que o normal. Isso faz o dígito ficar por cima do dois-pontos e da aspa. Precisamos aumentar essa distância para impedir essa sobreposição de caracteres;
2. Onde se lê "EC", mudar para "CE". Esperava encontrar esta informação em um dos script dumpados pelo dumper/inserter, mas não está lá;
3. Onde se lê "ÁREA {LETRA}-{NÚMERO}", a composição letra-número está ficando por cima da palavra "ÁREA", resultando em bugs como "ARE**B-1**", "ARE**G-2**", "ARE**X-3**". Também precisamos aumentar essa distância para impedir essa sobreposição de caracteres.

O arquivo na rom que contém esses gráficos chama-se "sub.bin", e situa-se na pasta "data" da rom. O mesmo também pode encontrado em avulso, na pasta "graficos" deste projeto.

![07](https://cloud.githubusercontent.com/assets/5247082/18368923/e6c7438a-75f8-11e6-99a7-574cf012167b.png)

**Comment by hansenhahn** [comment]
Notar que, ao salvar, as opções Sim e Não também aparecem erradas, conforme imagem abaixo. Além disso, FÁCIL está com erro no "Á".

![rockbr__372](https://user-images.githubusercontent.com/15808267/34629840-d2cdce0a-f250-11e7-90bf-904bf081a672.png)

**Comment by hansenhahn** [comment]
Corrigida a sobreposição da palavra ÁREA. Para tanto, é necessário alterar o valor original 88h por 98h nos seguintes endereços (todos do arm9.bin): 280A4h, 280D2h, 2810Ah. Repliquei essa alteração no arquivo subtitles.asm (responsável por todos as alterações no arm9.bin)

**Comment by hansenhahn** [comment]
Corrigido EC para CE. Para tanto é necessário alterar 28130h para 90h e 2818Ch para 80h

**Comment by hansenhahn** [comment]
Alterado o espaçamento das horas, para ficar igual a versão americana. Para tanto, foi necessário alterar os seguintes endereços para 20h: 27EEEh, 27F96h, 27FD0h, 2800Ch e 28048h

![init2](https://user-images.githubusercontent.com/15808267/34907989-83ebcf06-f86f-11e7-9123-42f538db270e.png)

**Comment by hansenhahn** [comment]
Corrigida a sobreposição do marcador em Sim e Não. Fica a pergunta se é possível dar um espaço antes do Não, para ficar igual ao Sim.
![yesno](https://user-images.githubusercontent.com/15808267/34908586-270c0b20-f879-11e7-8e9e-ead0530cd7cf.png)

Sobre o FÁCIL, que me parece bugado... está corrigido nas versões mais novas da tradução? Se estiver, podemos considerar essa tarefa fechada.

**Comment by hansenhahn** [comment]
Pelo que falei com o Solid, o FÁCIL é um erro na paleta, de fácil correção. Sobre o Sim/Não, empurrou-se o Não um tile para direita inserindo um espaço no texto. 

Podemos dar por completa esta tarefa!
