### ISSUE TITLE
Bugs visuais na tela de Game Over

### ISSUE THREAD

**Issue by leomontenegro6** [leomontenegro6/megaman-zx-traducao-ptbr#14]
Na tela de Game Over, há alguns bugs visuais, oriundos de sprites repetidos na tela.

A imagem abaixo ilustra o problema: No item de menu que está selecionado, da palavra "Carregar Jogo .... Novamente", a palavra cortada "novamente" no final corresponde aos mesmos tiles do item de menu escrito "Tentar Missão Novamente".

Como um workaround, o problema poderia ser solucionado através da remoção dos tiles equivalentes à palavra "novamente", mas isso impactaria nos textos de pelo menos duas opções de menu, que teriam de ser encurtadas, deixando o espaço para edição ainda menor do que já está.

A solução ideal seria encontrar o mapa de tiles, ou os bytes de OEM correspondentes aos sprites, e editá-los de modo a evitar a repetição de tiles e fazer melhor uso do espaço existente neste gráfico. Mas para encontrar esta informação, seria necessário uso de emuladores com recursos de debugging e tracing, bem como conhecimentos sobre depuração em jogos e aplicações compiladas para este portátil, e isto é algo que me falta no momento.

O arquivo na rom que contém esses gráficos chama-se "g_over.bin", e situa-se na pasta "data" da rom. O mesmo também pode encontrado em avulso, na pasta "graficos" deste projeto.

![mmzx_j__29434](https://cloud.githubusercontent.com/assets/5247082/18369396/df48fb8c-75fb-11e6-8f0c-d0781287b26b.png)

**Comment by leomontenegro6** [comment]
Após um pouco de depuração no No$GBA, consegui encontrar diversos tilemaps referentes às opções acima. No entanto, a estrutura dos tilemaps está uma bagunça, havendo inclusive ocorrências de um tilemap ser usado por dois ou mais gráficos.

Em seguida, sucedeu-se várias alterações de gráficos e tilemaps para ver se é possível remanejar o espaço. O resultado final não ficou perfeito, e isto foi o mais próximo de algo funcional que consegui chegar:

![mmzx_j-171219-214558](https://user-images.githubusercontent.com/5247082/34191186-d5959468-e523-11e7-9805-1f2fe5e64586.png)
![mmzx_j-171219-224215](https://user-images.githubusercontent.com/5247082/34191190-d69b37b4-e523-11e7-9a44-cd006082dec2.png)

**Comment by hansenhahn** [comment]
Gráfico disponível para tradução em asm\tool_g_over\asm_g_over_000

![gameover](https://user-images.githubusercontent.com/15808267/43689672-764a5b6e-98d4-11e8-8709-9d4cdcab0629.PNG)

**Comment by hansenhahn** [comment]
Gráficos reinseridos na ROM. Tanto as opções, quando o desenho de fundo estão agora corretos.

![gover](https://user-images.githubusercontent.com/15808267/44951515-d6370180-ae3c-11e8-806f-265c6cbb7641.png) ![gover2](https://user-images.githubusercontent.com/15808267/44951540-5cebde80-ae3d-11e8-80e5-626c45ecd94a.png)
