### ISSUE TITLE
Gráficos abreviados ou não-traduzidos na tela de configuração de botões

### ISSUE THREAD

**Issue by Flah-Los** [leomontenegro6/megaman-zx-traducao-ptbr#16]
Há tradução para tudo menos para o _Dash_ e _Custom_
Outro 'problema' seria as abreviações para _Princ._, _Sec._ e _Transf_.

Quanto a _Princ. Arma_ e _Sec Arma_, seria interessante, mesmo depois de resolvido o problema da abreviação, inverter os termos, para ficar de acordo com a concordância nominal.

![image](https://cloud.githubusercontent.com/assets/24319280/20839282/1a56575e-b893-11e6-899a-6348553a83a1.png)
https://s14.postimg.org/oxuxfrtgx/image.png

**Comment by leomontenegro6** [comment]
Alterei os tilemaps do arquivo "sub.bin" para corrigir essas abreviações. Segue o resultado:

![mmzx_j-171220-005622](https://user-images.githubusercontent.com/5247082/34191120-5603c5da-e523-11e7-8aef-574841d8fcba.png)

Também foram melhorados termos das abas "Ataque" e "Modo de Ação".

Essas alterações virão em uma atualização futura da tradução.
