### ISSUE TITLE
Transportar tela-título da versão americana para a japonesa

### ISSUE THREAD

**Issue by leomontenegro6** [leomontenegro6/megaman-zx-traducao-ptbr#17]
Apesar de ter sido feita em cima da rom japonesa para poder contar com o undub do áudio original, essa tradução ainda tem como objetivo primário seguir as nomenclaturas da versão americana: Megaman no lugar de Rockman, Biometal no lugar de Livemetal, etc.

Como tal, se fará necessário transportarmos a tela-título da versão americana para a japonesa. O caminho mais rápido para fazê-lo é copiando os arquivos "**title.bin**" e "**obj_fnt.bin**" de uma versão para outra, mas como esse arquivo é maior na versão americana, existe a possibilidade disso causar comportamentos imprevistos na rom, como travamentos em locais específicos. Talvez se faça necessário tentar reduzir seu tamanho para o mesmo da japonesa, ou em último caso alterar o arm9.bin para poder comportar esse novo arquivo.

Seguem imagens comparativas de ambos os arquivos, para auxiliar no processo:
![01](https://cloud.githubusercontent.com/assets/5247082/26566121/06834b9a-44c7-11e7-88c8-8bff601372a0.png)

![img](https://cloud.githubusercontent.com/assets/5247082/26563575/71f596c0-44aa-11e7-9011-a7fcf09535c6.png)

Ainda sobre a tela-título, há alguns gráficos a ser editados nela que ainda não foram encontrados, provavelmente por estarem comprimidos (A CONFIRMAR). Um deles é a mensagem "A NEW HERO... **ROCK ON** / **MEGAMERGE**" que antecede a tela-título do jogo em contextos específicos, aparecendo quando você dá game over e escolhe a opção "Sair do Jogo", ou quando você executa um soft reset pressionando os botões "L + R + Start + Select" simultaneamente:

| Japonesa | Americana |
|----------|-----------|
|![j1](https://cloud.githubusercontent.com/assets/5247082/26563576/71f6f09c-44aa-11e7-8614-503d6298f565.png)|![a1](https://cloud.githubusercontent.com/assets/5247082/26563572/71f35cb6-44aa-11e7-94ad-a56108ebb0b9.png)|
|![j2](https://cloud.githubusercontent.com/assets/5247082/26563573/71f4d442-44aa-11e7-8c12-d27deb296882.png)|![a2](https://cloud.githubusercontent.com/assets/5247082/26563574/71f566d2-44aa-11e7-9336-b4b1f6274cc8.png)|

Outro deles são os textos de copyright que aparecem no rodapé da tela-título, marcados em vermelho:

![cred](https://cloud.githubusercontent.com/assets/5247082/26563577/71f7ad0c-44aa-11e7-8e29-8dc708f3aff2.png)

**Comment by leomontenegro6** [comment]
Ao analisar a rom pelo LazyDS, encontrei alguns desses gráficos dentro do arquivo **title.bin**. Estavam comprimidos.

A tabela abaixo detalha minhas descobertas:

|Offset|Descrição|Tipo de Compressão|Codec
|-------|----------|-----------------------|-------
|0x000000A0|THE NEW HERO... ROCK ON.|8bpp linear|LZSS 0x10|
|0x000073D0|Tela-título, mais copyright|8bpp linear|LZSS 0x10|
|0x0000E234|MEGA SYSTEM laranja|4bpp linear reversed order|LZSS 0x10|

Para a edição do copyright, aparentemente a edição será bem simples. Já para os outros, isso envolverá manuseio de tilemaps.

**Comment by leomontenegro6** [comment]
Graças ao feedback e às dicas fornecidas por DiegoHH, consegui transportar / editar a maior parte dos elementos da tela-título americana, citadas nesta issue.

Em conversas no facebook / chat do canal do discord, fizemos o teste de transportar o **title_usa.bin** da versão americana para a japonesa, sobrescrevendo o **title.bin** original. Constatamos que, com isso, todos os elementos da tela-título foram de fato transportados para a versão japonesa.

Além disso, DiegoHH encontrou o logo em miniatura. Estava descomprimido dentro do **obj_fnt.bin**, em um conjunto de cores que dificultava ser enxergado a olho nu. Tendo isso em mãos, obtive o mesmo gráfico da rom americana e transportei seus tiles para o da rom japonesa, através do Tile Molester.

Seguem imagens para ilustrar as novas mudanças:

![logo_miniatura](https://user-images.githubusercontent.com/5247082/26855172-ec1aca4c-4aef-11e7-85b8-fbdcb96098a6.png) ![logo_letras](https://user-images.githubusercontent.com/5247082/26855179-f01677a4-4aef-11e7-9c12-8acdc0749fbd.png) ![logo_principal](https://user-images.githubusercontent.com/5247082/26855181-f3fc0d48-4aef-11e7-8a40-7c63f2e994df.png)

Para que possamos dar esta issue por concluída, está(ão) pendente(s) edição:

- THE NEW HERO... ROCK OK (agora alterado para *A NEW HERO... MEGAMERGE*, em função da transportação do **title_usa.bin** para a rom japonesa);
- MEGA SYSTEM laranja (associado à issue #21, logo deverá ser tratado lá).

**Comment by hansenhahn** [comment]
Consegui documentar e criar uma tool para abrir o arquivo title.bin. Além disso, foi possível montar alguns tilemaps, conforme as imagens abaixo. Pelo que percebi, os demais tilemaps não precisam de tradução (são, por exemplo, os personagens...)

![example_tiles](https://user-images.githubusercontent.com/15808267/34651764-e375c070-f3bb-11e7-8d02-83a1a3e5a283.PNG)

Os arquivos relacionados à esta issue encontram-se em "asm/tool_title".

A propósito, qual a correta tradução para "A NEW HERO... MEGAMERGE?"

**Comment by leomontenegro6** [comment]
A tradução, conforme a lógica da versão americana, é "UM NOVO HERÓI... MEGAMERGIRÁ".

**Comment by hansenhahn** [comment]
A NEW HERO MEGAMERGE feito

Foi necessário alterar o arm9.bin para acrescentar mais caracteres (editado no subtitles.asm)
![rockbr__18370](https://user-images.githubusercontent.com/15808267/34698057-4443ee0c-f4bd-11e7-9560-412063665aa4.gif)

Colocar acentos daria um trabalho.. é necessário??

**Comment by hansenhahn** [comment]
Inserida a tradução da tela branca. Foi necessário corrigir uns pequenos detalhes na imagem (SISTEMA estava deslocado 1px em relação à imagem laranja e havia alguns erros na paleta de cores)

![megasystem_b](https://user-images.githubusercontent.com/15808267/34906357-170b071a-f853-11e7-94c6-55ff1026353c.png)

Fica faltando a acentuação (alteração da fonte) de UM NOVO HEROI MEGAMERGIRA para dar como concluída a tarefa

**Comment by hansenhahn** [comment]
Adicionado acentos na animação.
![novo](https://user-images.githubusercontent.com/15808267/35014562-254b1142-faf8-11e7-9a4b-6b648dd9ab16.png)

Tarefa concluída!
