### ISSUE TITLE
Editar gráfico "WARNING", que antecede as batalhas contra chefes

### ISSUE THREAD

**Issue by leomontenegro6** [leomontenegro6/megaman-zx-traducao-ptbr#18]
Desde o Megaman X4 até então, todo jogo da franquia exibe uma mensagem "WARNING" na tela, imediatamente antes de uma batalha contra um chefe. Tradicionalmente, optamos por traduzi-la para "ALERTA", e inclusive já o fizemos em traduções para o Megaman X4 e Megaman X5.

Mas isso ainda está pendente no Megaman ZX. Tudo indica que esse gráfico está no arquivo **vx/WARNING.vx**, que possui mesma extensão e supostamente mesmo formato dos arquivos de vídeo. E como até então não existe nenhum encoder funcional para gerar vídeos em ActImage para jogos de DS, talvez não tenhamos o que fazer nesse caso.

![warning](https://cloud.githubusercontent.com/assets/5247082/26563739/46a2b4dc-44ad-11e7-8d47-c131540e3080.png)

No entanto, falta ainda uma análise para confirmar se é possível modificar este arquivo não. E uma vez que não o seja, estudar a possibilidade de usar o arquivo da tradução espanhola, existente na versão européia do jogo.

![atencion](https://cloud.githubusercontent.com/assets/5247082/26563738/468bb8d6-44ad-11e7-8eea-8282bab04f64.png)

**Comment by hansenhahn** [comment]
Pude verificar que, na ROM europeia, em espanhol, o Warning (ou Atención) é gerado da seguinte forma:
* Um tilemap e um tileset geram a imagem completa no BG3
* Através do registro 0400001C (Scrolling do BG3), alterando a posição inicial da tela desse background a cada irq de H-Blank, é possível simular o efeito

Bom, ainda não achei os arquivos que contém o tilemap e tileset, muito menos verifiquei a rotina que faz a animação, porém acredito que, com o que foi visto, é possível portar para a ROM japonesa, sem ficar preso ao vídeo WARNING.vx.

![capturar](https://user-images.githubusercontent.com/15808267/42425673-bcac7112-82f6-11e8-8503-80085ac08993.JPG)

**Comment by hansenhahn** [comment]
No fim, foi mais fácil do que parecia. Nem a rom europeia, nem a rom japonesa, usavam o arquivo de vídeo. O tilemap e tileset encontram-se no arquivo game_parm.bin.

Alterando game_parm.bin da ROM japonesa pela versão espanhola, foi possível "rodar" a animação do Atención.
![warning](https://user-images.githubusercontent.com/15808267/42426036-c38d0b14-82fa-11e8-9f9c-3b6dab2ffefa.png)

Em suma, basta traduzir o tileset/tilemap e está feito.

**Comment by hansenhahn** [comment]
Extrai o gráfico para a pasta asm\tool_game_parm\asm_game_parm_000\000_000_image.bin

Fico no aguardo da edição.

**Comment by leomontenegro6** [comment]
editado:

![warning copy](https://user-images.githubusercontent.com/5247082/42487401-458b3a28-83d7-11e8-9e15-0a5accfd5d60.png)

também commitei o binário.

**Comment by hansenhahn** [comment]
Issue concluída. Como a edição é pequena, não fiz uma tool para automatizar a recriação do game_parm.bin. O tilemap e tileset são gerados automaticamente.

![warning1](https://user-images.githubusercontent.com/15808267/42547101-cd47f3d8-8496-11e8-9c2e-40e1bc97cd31.png) ![warning2](https://user-images.githubusercontent.com/15808267/42547103-d03ff914-8496-11e8-99ab-d7e5da18952e.png) ![warning3](https://user-images.githubusercontent.com/15808267/42547107-d3b999c4-8496-11e8-89bd-bc4653fce63a.png) ![warning4](https://user-images.githubusercontent.com/15808267/42547110-d75a736e-8496-11e8-9b21-814dad6c4335.png)

PS: O background preto é bug do emulador, não da alteração.

**Comment by BLake020W** [comment]
Alguien sabe si se puede editar los diálogos de los personajes? para crear un juego o algo?
