### ISSUE TITLE
Gráficos "MISSION START", "MISSION COMPLETE" e "GAME OVER" localizados, mas não traduzidos por limitações técnicas

### ISSUE THREAD

**Issue by leomontenegro6** [leomontenegro6/megaman-zx-traducao-ptbr#19]
No contexto do jogo, pegamos várias missões para cumprir. Sempre que pegamos uma missão, aparece na tela a mensagem "MISSION START". Quando a concluímos, aparece "MISSION COMPLETE". Se perder todas as vidas dentro de uma missão, aparece "MISSION FAILED". E se perder todas as vidas fora de uma missão, aparece "GAME OVER".

![missionstart](https://cloud.githubusercontent.com/assets/5247082/26563965/4d3990f0-44b1-11e7-82b4-4846a65348ad.png) ![missioncomplete](https://cloud.githubusercontent.com/assets/5247082/26564129/85b4724a-44b3-11e7-9ef4-fe4aebf548c9.png)
![missionfailed](https://cloud.githubusercontent.com/assets/5247082/26564128/85b168ac-44b3-11e7-9361-21fdc8dc02d2.png) ![gameover](https://cloud.githubusercontent.com/assets/5247082/26563966/4d3c9bc4-44b1-11e7-8bbf-eb8eb17c0c24.png)

Todas essas mensagens ainda encontram-se pendentes tradução, por limitações técnicas de romhacking na rom. Elas são geradas com uma única fonte, que por sua vez possui apenas os caracteres necessários para exibir esses textos. Por não serem gráficos individuais, seu processo de edição torna-se um pouco mais complicado, pois se faz necessário encontrar os bytes de OAM equivalentes para podermos manipular a posição das letras no gráfico.

Teoricamente, é algo muito similar ao que ocorreu no gráfico "Game Over" do jogo "Legend of Zelda - Minish Cap", de GBA.

Os gráficos da fonte situam-se no arquivo "**obj_fnt.bin**", e estão totalmente descomprimidos, sendo perfeitamente visíveis pelo Tile Molester com o codec "4bpp linear, reversed-order". A tabela abaixo ilustra os offsets, tanto dos gráficos como das paletas:

| Nome | Offset Gráfico | Offset Paleta |
|--------|----------------|---------------|
|MISSION START|0x4D228|0x4DB48|
|MISSION COMPLETE|0x4E688|0x4F188|
|MISSION FAILED|0x4C728|0x4D228|
|GAME OVER|0x4DB68|0x4E668|

**Comment by hansenhahn** [comment]
Fiz todo o debug necessário para verificar como o jogo carrega o tileset para a VRAM e como o mesmo monta as OAMs para cada letra.

Essas informações estão espalhadas nos seguintes arquivos: arm9.bin , obj_dat.bin e obj_fnt.bin. Infelizmente, a leitura de dados, tanto de obj_dat.bin, quanto de obj_fnt.bin, é feita linearmente, então não é possível simplesmente "alterar os ponteiros" e jogar os dados para o fim do arquivo. Foi necessário criar um script que fizesse o unpack/repack desses dois arquivos. Feito a divisão desses arquivos, as alterações a seguir foram feitas no arquivo 053 de ambos os arquivos.

Usando MISSION START como exemplo:
* Na VRAM é carregado os seguintes tiles, a partir do endereço 0x0640F500: MSONTARI
* Para traduzir MISSION START para INICIAR MISSÃO, primeiro é necessário adicionar mais uma letra ao tileset, de modo a termos MSONÃARIC.
  * A letra a mais exige a cópia de mais 8 tiles para a VRAM (já que o tamanho 16x32 é o suficiente para essa OAM)
  * Para tanto, foi necessário alterar o valor 0x0900 para 0x0A00 (+256 bytes) em 4C6F0h do arquivo obj_fnt.bin
  * Adicionou-se 256 bytes ao fim do caractere I (não corrigi os ponteiros dos próximos gráficos neste teste), onde desenhou-se o caractere C.
* O ponteiro para MISSION START está em E4F68h no arquivo arm9.bin
  * MISSIONSTART\0 -> 0A  0B  0C  0C  0B  0D  0E  0C  0F  10  11  0F  FF que foi trocado para INICIARMISSÃO\0 -> 0B  0E  0B  28  0B  10  11  0A  0B  0C  0C  0F  0D  FF
  * A letra nova foi mapeada em 28h porque temos, originalmente, 40 caracteres totais nos 4 tilesets.
  * O T foi trocado por Ã.
* Nesse momento foi necessária a expansão do arquivo 053 do obj_dat. Foi preciso criar uma entrada a mais na segunda tabela de ponteiros (a partir do endereço 8BECh), responsável por converter MISSIONSTART para MISONTAR. Adicionei a entrada 28h apontando para o caractere C.
* Em seguida, foi necessário acrescentar mais uma entrada na primeira tabela de ponteiros, que mapeia o caractere ao número do tile da VRAM (relativo, somar 1EAh a esse valor)
  * 00 10 04 06 08 0A 0C 0E 12 (o 12h é a letra nova C)
* Por fim, é necessário modificar a posição X das OAMs, de modo a considerar a letra extra. Para tanto, modificar a partir do endereço E5004h em arm9.bin . Como temos um caractere a mais, talvez seja necessário jogar esses valores para o fim do arquivo. O ponteiro para essas OAMs está em E4F88h.

Enfim... para facilitar a edição, além dos scripts de unpack/repack, transformei o arquivo 053 do obj_dat.bin num script ASM (ver repositório). Assim fica mais fácil fazer a expansão das tabelas para aceitar novos caracteres. O resultado parcial/final (não está 100% alinhado e o desenho do Ã é um teste) pode ser visto na figura abaixo.

![mission](https://user-images.githubusercontent.com/15808267/34628719-89fe71ba-f24c-11e7-9acf-5c7abb849c42.jpg) ![rockbr__30919](https://user-images.githubusercontent.com/15808267/34629488-6fd22a68-f24f-11e7-9245-7631b38c4766.gif)


Durante os testes, foi verificado o travamento da ROM. Isso foi consertado. Viu-se que o arquivo 053 gerado pelo assembler não tinha tamanho múltiplo de 4, e nem as tabelas estavam alinhadas com endereço múltiplo de 4.

**Comment by hansenhahn** [comment]
Organizei a geração dos arquivos obj na pasta tool_obj e criei scripts (batches) para automatizar a geração da rom com as modificações.

Criei o asm do arquivo 053 de obj_fnt, permitindo a expansão dos tilesets sem prejudicar os outros gráficos. Por fim, adicionei a tradução de MISSION FAILED para MISSÃO FRACASSADA.

![mission_failed](https://user-images.githubusercontent.com/15808267/34642352-8de56764-f2f8-11e7-877c-90b30b313a9c.jpg) ![rockbr__5370](https://user-images.githubusercontent.com/15808267/34642344-72a8d5da-f2f8-11e7-927a-524ee4ea2d77.gif)

**Comment by hansenhahn** [comment]
GAME OVER para FIM DE JOGO
![gameover](https://user-images.githubusercontent.com/15808267/34643663-52d0f0dc-f30f-11e7-96e9-dc3930b21a4d.jpg) ![rockbr__5052](https://user-images.githubusercontent.com/15808267/34643662-4ecf9a1a-f30f-11e7-95da-4349eb83a908.gif)

**Comment by hansenhahn** [comment]
MISSION COMPLETE para MISSÃO CONCLUÍDA (sem gif dessa vez 👎 )
![mission_complete](https://user-images.githubusercontent.com/15808267/34644442-da25da9e-f31d-11e7-8956-e0844332acd8.jpg)

**Comment by hansenhahn** [comment]
Ok, issue concluída e documentada, caso seja necessário fazer alguma alteração futura.
