### ISSUE TITLE
Traduzir backgrounds ROCK/MEGA System "SISTEMA MEGA"

### ISSUE THREAD

**Issue by leomontenegro6** [leomontenegro6/megaman-zx-traducao-ptbr#21]
No contexto do jogo, pessoas comuns se conectam a artefatos chamados de "Biometal" (BM), e ao acessar o sistema que há neles, conseguem se fundir com os BMs e usar seus poderes.

Na versão japonesa, o sistema que há nos Biometais se chama "R.O.C.K. System", onde a sigla ROCK significa "Rebirth of Crystalized Knowledge". Já na versão americana, foi adaptado para "M.E.G.A. System", onde a sigla MEGA significa: "Meta-Encapsulated Granule Awareness".

![rock_mega](https://cloud.githubusercontent.com/assets/5247082/26564238/e2b809f6-44b4-11e7-816d-c5615fe9537a.png)

Já na nossa tradução, por seguir a linha dos termos ocidentais, mudei isso para "Sistema M.E.G.A.", com a siga significando "Meta-Encapsulador Gnóstico de Antepassados". A imagem abaixo é um esboço dessa edição.

![sistema_mega](https://cloud.githubusercontent.com/assets/5247082/26564254/0bf9cd7c-44b5-11e7-82ec-9fc89c5e1aac.png)

No entanto, nenhum desses gráficos foram alterados ingame até o presente momento. São vários backgrounds, distribuídos em múltiplos arquivos, e possuindo tilemaps bastante bagunçados para permitir a total edição desse gráfico. Se possível, uma ferramenta básica para extração e reinserção desse gráfico, em função dos tilemaps, ajudaria bastante nesse processo.

Segue abaixo uma lista de locais onde esses arquivos podem ser encontrados:

| Nome | Arquivo | Offset Gráfico | Offset Paleta |
|------|------|----------------|---------------|
|ROCK System (fundo laranja)|title.bin (comprimido LZSS 0x10)|0x000073D0|desconhecido|
|R.O.C.K. System (fundo azul)|sub.bin|começo|0x2F804|
|ROCK System (fundo azul)|elf.bin|começo|0x3B48|

**Comment by leomontenegro6** [comment]
DiegoHH recentemente desenvolveu tools para facilitar a edição desses gráficos, com rotinas de auto-montagem de tilemaps para esses tipos de gráficos.

Tendo em vista isso, alguns gráficos tornaram-se disponíveis para edição, com um deles sendo o abaixo:

![captura de tela de 2018-01-08 23 35 51](https://user-images.githubusercontent.com/5247082/34702524-f3afc9d8-f4cc-11e7-875e-95751264457f.png)

**Comment by hansenhahn** [comment]
Gráfico laranja INGAME:

![megasystem](https://user-images.githubusercontent.com/15808267/34749673-ead9e646-f589-11e7-90bd-94e4d340e5de.png)

Para fechar a tradução da tela inicial, ficou faltando o gráfico branco que é mostrado antes do laranja, extraído para o arquivo asm_002_title\002_1_image.bin . A paleta de cores é a 4.

Além disso reescrevi as tools relacionadas para automatizar 100% a recriação do title.bin. Por fim, passei a usar o pypy buscando executar de forma mais eficiente os scripts python.

**Comment by hansenhahn** [comment]
Manipulação do arquivo elf.bin concluída. O ROCK SYSTEM azul está disponível na pasta \asm\tool_elf\asm_elf_004_002\002_image.bin . A paleta de cores está em \asm\tool_elf\old_elf\ptr_table_1\004\002_palette.bin. Ao editar o arquivo, criar um novo 002_imagem_novo.bin.

![capturar](https://user-images.githubusercontent.com/15808267/34909970-29b4fcd2-f893-11e7-95ca-4e61188f7a59.PNG)

**Comment by hansenhahn** [comment]
Mais um check
![megazul](https://user-images.githubusercontent.com/15808267/35016502-fbc4342c-faff-11e7-9e75-bcd1884ee1a6.png)

Fica faltando o background do menu.

**Comment by hansenhahn** [comment]
Os arquivos que compõem o sub.bin são um pouco diferente dos demais (title.bin e elf.bin). Por exemplo, não existe uma tabela de ponteiros no arquivo dos tilemaps (005.bin)

Fiz um teste rápido e manual e pude extrair um dos menus.
![capturar](https://user-images.githubusercontent.com/15808267/35018225-ae2121fa-fb07-11e7-97fd-5b86b88e2b55.PNG)

**Comment by hansenhahn** [comment]
Último gráfico.
![capturar2](https://user-images.githubusercontent.com/15808267/35019178-a9fb95d8-fb0c-11e7-9080-a68254aeb85a.PNG)

Gráficos disponíveis em tool_sub\asm_sub_000_001 e tool_sub\asm_sub_000_002 . Não procurei a paleta de cores.

**Comment by hansenhahn** [comment]
Primeira imagem ok. Segunda imagem, ao inserir, quebrou a tela do lado, onde fica o mapa. Além disso, parte do fundo está nos sprites de item.. é necessário achá-los ainda.

![teste](https://user-images.githubusercontent.com/15808267/36111312-dd2d0878-100c-11e8-9c07-fbc21d66817d.png)

**Comment by hansenhahn** [comment]
![teste2](https://user-images.githubusercontent.com/15808267/36113058-b59201c8-1012-11e8-9946-5e44b42e06d9.png)

Feito. A tela com o mapa usava o mesmo tileset da tela acima. Sendo assim, era necessário atualizar seu tilemap também.

**Comment by hansenhahn** [comment]
Fechou. Disponível em "asm\tool_sub\asm_sub_000_003\003_001_image.bin"

![003](https://user-images.githubusercontent.com/15808267/36113595-7870241c-1014-11e8-835a-610b1b568ddc.PNG)

**Comment by hansenhahn** [comment]
![megasystem](https://user-images.githubusercontent.com/15808267/36235724-74190f3e-11d9-11e8-9f7a-3452245e0103.png)

Apenas corrigir os pixel cinza de ITEM, alinhar o MEGA e fechou!

**Comment by hansenhahn** [comment]
Ok, issue concluída e documentada, caso seja necessário fazer alguma alteração futura.
