### ISSUE TITLE
Text  displays the "@" character instead of a line break

### ISSUE THREAD

**Issue by luatsenpai** [leomontenegro6/megaman-zx-traducao-ptbr#25]
Hello, I'm using your tool and when I run the mmzx_inserter script and then put it into the game, the text displays @ as shown in the image.
<img src="https://i.ibb.co/TBpjhk3/mzx-12782.png" alt="mzx-12782" border="0">

Php version I'm using: 7.4.33 for windowa
How to fix it? Hope you reply, thank you very much!

**Comment by leomontenegro6** [comment]
The dumper/inserter tool I wrote in PHP was developed in Linux (Ubuntu), and some minor stuff might change regarding how scripts are dumped or inserted. It should work fine on Linux, but cause issues like yours on Windows.

You should have more luck by installing Ubuntu on your Windows machine through WSL2, and then using PHP from there.

**Comment by luatsenpai** [comment]
Solved, thank you very much
<img src="https://i.ibb.co/YbQrsmR/mzx-28530.png" alt="mzx-28530" border="0">
