### ISSUE TITLE
Trechos de diálogos incompletos.

### ISSUE THREAD

**Issue by sksdutra** [leomontenegro6/megaman-zx-traducao-ptbr#5]
Necessário se faz verificar trechos de diálogos que estão incompletos no script q02_en1 em relação ao q02_en2.

**Comment by sksdutra** [comment]
Decidido que provavelmente é um mecanismo interno do jogo.

**Comment by leomontenegro6** [comment]
Verifiquei os scripts "talk_q02_en1" e "talk_q02_en2" originais na rom americana. Constei que os diálogos no "en1" também estão incompletos em relação ao "en2". Provavelmente, isso ocorre porque o jogo, internamente, referencia apenas o script "en2" tanto para o protagonista homem (Vent) como para a feminina (Aile), assim ignorando o "en1".

No entanto, para confirmar isto, é necessário testar ingame. E como esse script equivale a uma das sidequests que só aparecem lá pela metade do jogo, deve demorar para chegar lá.

Enquanto isso, como não temos a certeza absoluta nesse caso, vamos traduzir esses scripts do jeito que puder, ignorando os trechos incompletos.

Além disso, para estes scripts particularmente, como é um só para ambos os personagens, é bom traduzir os textos de forma mais "unissex" possível, evitando termos que apontem claramente para o gênero masculino / feminino do protagonista. Exemplos:

Ao invés de "Você é um(a) transportador(a)?",
Colocar "Você é da transportadora" ou "Você trabalha na transportadora".

Algo assim.
